services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # We store metrics in created volume so they live even after container restart 
      - prometheus_data:/prometheus
      # We mount file with prometheus configuration from host to the container 
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/prometheus/rules.yaml:/etc/prometheus/rules.yaml
      
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - /etc/alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Same as with prometheus 
      - grafana_data:/var/lib/grafana
      # Mounts datasource and dashboard provides configs from host
      - /etc/grafana/provisioning:/etc/grafana/provisioning
      # Mounts dashboard JSON files downloaded from S3
      - /etc/grafana/dashboards:/etc/grafana/dashboards
    # Prometheus has to be up before grafana
    depends_on:
      - prometheus

volumes:
  # Grafana data that stays between container restarts
  grafana_data:
  # Prometheus metrics that stays between container restarts 
  prometheus_data: