name: Deploy Image and Infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/app:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/app:latest
            
  terraform-plan-network:
    name: Terraform plan network
    runs-on: ubuntu-latest
    needs: build
    outputs:
      exitcode: ${{ steps.plan_network.outputs.exitcode }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/network
        run: terraform init

      - name: Terraform format check
        working-directory: ./terraform/network
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform/network
        run: terraform validate

      - name: Terraform plan with output
        working-directory: ./terraform/network
        id: plan_network
        run: |
          terraform plan -out=tfplanNETWORK -detailed-exitcode
          exitcode=$?
          if [ $exitcode -eq 1 ]; then
            exit 1
          fi
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: steps.plan_network.outputs.exitcode == '2'
        with:
          name: tfplanNETWORK
          path: ./terraform/network/tfplanNETWORK
  
  manual-approve-network:
    name: Manual approval
    runs-on: ubuntu-latest
    if: needs.terraform-plan-network.outputs.exitcode == '2'
    needs: terraform-plan-network
    permissions:
      issues: write
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: sadowski-damian
          minimum-approvals: 1
          issue-title: "Manual Approval required for Terraform Apply"
          issue-body: "Please approve or deny the deployment"
  
  terraform-apply-network:
    name: Terraform apply
    runs-on: ubuntu-latest
    if: needs.terraform-plan-network.outputs.exitcode == '2'
    needs: [manual-approve-network, terraform-plan-network]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/network
        run: terraform init

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplanNETWORK
          path: ./terraform/network/

      - name: Terraform apply
        working-directory: ./terraform/network
        run: terraform apply -auto-approve tfplanNETWORK
        
  terraform-plan-db:
    name: Terraform plan db
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.plan_db.outputs.exitcode }}
    if: needs.terraform-apply-network.result == 'success' || needs.terraform-apply-network.result == 'skipped'
    needs: terraform-apply-network
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/db
        run: terraform init

      - name: Terraform format check
        working-directory: ./terraform/db
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform/db
        run: terraform validate

      - name: Terraform plan with output
        working-directory: ./terraform/db
        id: plan_db
        run: |
          terraform plan -out=tfplanDB -detailed-exitcode
          exitcode=$?
          if [ $exitcode -eq 1 ]; then
            exit 1
          fi
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: steps.plan_db.outputs.exitcode == '2'
        with:
          name: tfplanDB
          path: ./terraform/db/tfplanDB

  manual-approve-db:
    name: Manual approval
    runs-on: ubuntu-latest
    if: needs.terraform-plan-db.outputs.exitcode == '2'
    needs: terraform-plan-db
    permissions:
      issues: write
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: sadowski-damian
          minimum-approvals: 1
          issue-title: "Manual Approval required for Terraform Apply"
          issue-body: "Please approve or deny the deployment"

  terraform-apply-db:
    name: Terraform apply
    runs-on: ubuntu-latest
    if: needs.terraform-plan-db.outputs.exitcode == '2'
    needs: [ manual-approve-db, terraform-plan-db ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/db
        run: terraform init

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplanDB
          path: ./terraform/db/

      - name: Terraform apply
        working-directory: ./terraform/db
        run: terraform apply -auto-approve tfplanDB

  terraform-plan-infra:
    name: Terraform plan infra
    runs-on: ubuntu-latest
    if: needs.terraform-apply-network.result == 'success' || needs.terraform-apply-network.result == 'skipped'
    needs: terraform-apply-network
    outputs:
      exitcode: ${{ steps.plan_infra.outputs.exitcode }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/infra
        run: terraform init

      - name: Terraform format check
        working-directory: ./terraform/infra
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform/infra
        run: terraform validate

      - name: Terraform plan with output
        working-directory: ./terraform/infra
        id: plan_infra
        run: |
          terraform plan -out=tfplanINFRA -detailed-exitcode
          exitcode=$?
          if [ $exitcode -eq 1 ]; then
            exit 1
          fi
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: steps.plan_infra.outputs.exitcode == '2'
        with:
          name: tfplanINFRA
          path: ./terraform/infra/tfplanINFRA
          
  manual-approve-infra:
    name: Manual approval 
    runs-on: ubuntu-latest
    if: needs.terraform-plan-infra.outputs.exitcode == '2'
    needs: terraform-plan-infra
    permissions: 
      issues: write
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: sadowski-damian
          minimum-approvals: 1
          issue-title: "Manual Approval required for Terraform Apply"
          issue-body: "Please approve or deny the deployment"
    
  terraform-apply-infra:
    name: Terraform apply
    runs-on: ubuntu-latest
    if: needs.terraform-plan-infra.outputs.exitcode == '2'
    needs: [manual-approve-infra, terraform-plan-infra]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/infra
        run: terraform init
      
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplanINFRA
          path: ./terraform/infra/

      - name: Terraform apply
        working-directory: ./terraform/infra
        run: terraform apply -auto-approve tfplanINFRA
  
  write-to-db:
    name: Register deploy in DB
    runs-on: ubuntu-latest
    needs: [terraform-apply-infra, terraform-apply-db, terraform-apply-network]
    if: |
      (needs.terraform-apply-network.result == 'success' || needs.terraform-apply-network.result == 'skipped') &&
      (needs.terraform-apply-infra.result == 'success' || needs.terraform-apply-infra.result == 'skipped') &&
      (needs.terraform-apply-db.result == 'success' || needs.terraform-apply-db.result == 'skipped')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform initialization
        working-directory: ./terraform/infra
        run: terraform init
        
      - name: Trigger instance refresh
        if: needs.terraform-apply-infra.result == 'skipped'
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name main-asg --preferences MinHealthyPercentage=50,InstanceWarmup=300                                                                                               
          aws autoscaling wait instance-refresh-succeeded --auto-scaling-group-name main-asg                                                                                                                     

      - name: Wait for instances
        if: needs.terraform-apply-infra.result == 'success'
        run: sleep 120
        
      - name: Register Deployment in DB
        run: |
          ALB_DNS=$(terraform -chdir=./terraform/infra output -raw alb_dns_name)
          API_KEY=$(aws ssm get-parameter --name "/prod/api-key" --query "Parameter.Value" --output text --with-decryption)
          curl -X POST "http://$ALB_DNS/deploys" -H "X-Api-Key: $API_KEY" -H "Content-Type: application/json" -d @- <<EOF                     
          {                                                                                                                                                  
          "commitSha": "${{ github.sha }}",
          "author": "${{ github.actor }}",                                                                                       
          "message": "${{ github.event.head_commit.message }}",
          "committedAt": "${{ github.event.head_commit.timestamp }}"                                                                                             
          }
          EOF 
      
    

