name: Deploy Image and Infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/app:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/app:latest

  terraform-network-plan:
    name: Terraform plan network
    runs-on: ubuntu-latest
    needs: build
    outputs:
      exit-code-network: ${{ steps.network-plan.outputs.exit-code }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: ./terraform/network
        run: terraform init

      - name: Terraform format check
        working-directory: ./terraform/network
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform/network
        run: terraform validate
      
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terraform plan
        working-directory: ./terraform/network
        id: network-plan
        run: |
          set +e
          terraform plan -detailed-exitcode -input=false -out=tfplan
          exit_code=$?
          echo "exit-code=$exit_code" >> "$GITHUB_OUTPUT"
          set -e
          if [ $exit_code -eq 2 ]; then
            echo "There are pending changes."
            exit 0
          elif [ $exit_code -eq 0 ]; then
            echo "No changes detected in the Terraform plan."
            exit 0
          else
            echo "Terraform plan failed."
            exit 1
          fi

  terraform-network-apply:
    name: Terraform apply network
    runs-on: ubuntu-latest
    if: ${{ needs.terraform-network-plan.outputs.exit-code-network == 2 }}
    needs: terraform-network-plan
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: ./terraform/network
        run: terraform init

      - name: Terraform apply
        working-directory: ./terraform/network
        run: terraform apply -auto-approve

  terraform-db-plan:
    name: Terraform plan db
    runs-on: ubuntu-latest
    if: ${{ needs.terraform-network-apply.result == 'success' || needs.terraform-network-apply.result == 'skipped' }}
    outputs:
      exit-code-db: ${{ steps.db-plan.outputs.exit-code }}
    needs: terraform-network-apply
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: ./terraform/db
        run: terraform init

      - name: Terraform format check
        working-directory: ./terraform/db
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform/db
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform/db
        id: db-plan
        run: |
          set +e
          terraform plan -detailed-exitcode -input=false -out=tfplan
          exit_code=$?
          echo "exit-code=$exit_code" >> "$GITHUB_OUTPUT"
          set -e
          if [ $exit_code -eq 2 ]; then
            echo "There are pending changes."
            exit 0
          elif [ $exit_code -eq 0 ]; then
            echo "No changes detected in the Terraform plan."
            exit 0
          else
            echo "Terraform plan failed."
            exit 1
          fi

  terraform-db-apply:
    name: Terraform apply db
    runs-on: ubuntu-latest
    if: ${{ needs.terraform-db-plan.outputs.exit-code-db == 2 }}
    needs: terraform-db-plan
    environment: db-apply
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: ./terraform/db
        run: terraform init

      - name: Terraform apply
        working-directory: ./terraform/db
        run: terraform apply -auto-approve

  terraform-infra-plan:
    name: Terraform plan infra
    runs-on: ubuntu-latest
    needs: terraform-network-apply
    outputs:
      exit-code-infra: ${{ steps.infra-plan.outputs.exit-code }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: ./terraform/infra
        run: terraform init

      - name: Terraform format check
        working-directory: ./terraform/infra
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform/infra
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform/infra
        id: infra-plan
        run: |
          set +e
          terraform plan -detailed-exitcode -input=false -out=tfplan
          exit_code=$?
          echo "exit-code=$exit_code" >> "$GITHUB_OUTPUT"
          set -e
          if [ $exit_code -eq 2 ]; then
          echo "There are pending changes."
          exit 0
          elif [ $exit_code -eq 0 ]; then
          echo "No changes detected in the Terraform plan."
          exit 0
          else
          echo "Terraform plan failed."
          exit 1
          fi

  terraform-infra-apply:
    name: Terraform apply infra
    runs-on: ubuntu-latest
    if: ${{ needs.terraform-infra-plan.outputs.exit-code-infra == 2 }}
    needs: terraform-infra-plan
    environment: infra-apply
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: ./terraform/infra
        run: terraform init

      - name: Terraform apply
        working-directory: ./terraform/infra
        run: terraform apply -auto-approve

  instance-refresh:
    name: Instance refresh
    runs-on: ubuntu-latest
    if: |
      (needs.terraform-infra-apply.result == 'success' || needs.terraform-infra-apply.result == 'skipped') &&
      (needs.terraform-db-apply.result == 'success' || needs.terraform-db-apply.result == 'skipped') &&      
      (needs.terraform-network-apply.result == 'success' || needs.terraform-network-apply.result == 'skipped') 
    needs: [terraform-network-apply, terraform-db-apply, terraform-infra-apply]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger instance refresh
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name main-asg --preferences MinHealthyPercentage=50,InstanceWarmup=300